version: "3.9"
services:
  web-vue:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/app
    tty: true
    ports:
      - "5173:5173"
#    command: sh -c "npm rebuild esbuild && yarn dev"
